Ability to combine multiple response projections #985
kobylynskyi/graphql-java-codegen pull request #1031
Opened 2023-02-20 01:57 UTC by kobylynskyi

---

### Description

Related to #985

---

Changes were made to:
- [X] Codegen library - Java
- [ ] Codegen library - Kotlin
- [ ] Codegen library - Scala

2023-02-21 02:03 UTC, kobylynskyi commented
@jxnu-liguobin
I've made some changes to kotlin/scala `.ftl`s and would appreciate if you take a look at it and possibly make some adjustments too.
Thanks!

2023-02-21 02:48 UTC, jxnu-liguobin commented on src/main/resources/templates/scala-lang/parametrized_input.ftl
> +    override def deepCopy(): ${className} {
```suggestion
    override def deepCopy(): ${className} = {
```

2023-02-21 02:50 UTC, jxnu-liguobin commented on src/main/resources/templates/scala-lang/parametrized_input.ftl
> +        val parametrizedInput = ${className}()
Unable to use new, and then assign values ​​one by one.
should be
A(
field1,field2,....
)

2023-02-21 02:52 UTC, jxnu-liguobin commented on src/main/resources/templates/kotlin-lang/parametrized_input.ftl
> +    <#if fields?has_content>
the same as scala.
should be
A(
field1,field2,....
)

2023-02-21 02:58 UTC, jxnu-liguobin commented on src/main/resources/templates/scala-lang/response_projection.ftl
> +            for (field <- projection.fields.values) {
```suggestion
            for (field <- projection.fields.values.asScala) {
```

2023-02-21 02:58 UTC, jxnu-liguobin commented on src/main/resources/templates/scala-lang/response_projection.ftl
> +                    for (field <- projection.fields.values) {
```suggestion
                    for (field <- projection.fields.values.asScala) {
```

2023-02-21 02:59 UTC, jxnu-liguobin commented on src/main/resources/templates/scala-lang/response_projection.ftl
> +    override def deepCopy$(): ${className} = ${className}(this)
```suggestion
    override def deepCopy$(): ${className} = new ${className}(this)
```

2023-02-21 03:05 UTC, jxnu-liguobin requested changes
I left some comments, you can try to make changes, or wait for me to make changes sometime in the evening.

2023-02-21 05:09 UTC, jxnu-liguobin commented
plz see https://github.com/kobylynskyi/graphql-java-codegen/pull/1032

2023-02-22 01:42 UTC, kobylynskyi commented
@jxnu-liguobin thank you for your feedback, I've applied your changes to templates in this PR. Please take a look.

2023-02-22 02:56 UTC, jxnu-liguobin submitted a review, later dismissed

2023-02-22 12:15 UTC, merged