Upstream/985 combine multiple response projections
kobylynskyi/graphql-java-codegen pull request #1032
Opened 2023-02-21 05:08 UTC by jxnu-liguobin

---

### Description

Related to #ISSUE_NUMBER

---

Changes were made to:
- [ ] Codegen library - Java
- [ ] Codegen library - Kotlin
- [ ] Codegen library - Scala
- [ ] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin

2023-02-21 05:13 UTC, jxnu-liguobin commented
In order to verify major changes, I put Scala and kotlin files into the test module to ensure that they can be compiled, but at present, I need to manually execute GraphQLCodegenVerifyCompileTest.java

2023-02-22 01:36 UTC, kobylynskyi requested changes

2023-02-22 01:36 UTC, kobylynskyi commented on build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.8.20-Beta'
@jxnu-liguobin I would like not to add kotlin code and dependencies to the main project. instead, please add this as part of example kotlin plugin which we already have.

2023-02-22 01:54 UTC, jxnu-liguobin commented on build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.8.20-Beta'
Yes. We can update the sample synchronously when major changes occur.

2023-02-22 01:54 UTC, closed without merging

2023-02-22 01:55 UTC, jxnu-liguobin commented on build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.8.20-Beta'
The template changes in this PR have been verified, closed it