Made possible to use custom templates
kobylynskyi/graphql-java-codegen pull request #1048
Opened 2023-03-17 07:10 UTC by velo

---

### Description

Added the configuration for manually selecting templates.  This would allow anyone that needs/wants to modify a output, to do it by themselves.

For instance, I'm would like to use java record with lombok annotations, by using a custom template I can do it.

Related to #146 and potentially many others

---

Changes were made to:
- [x] Codegen library - Java
- [x] Codegen library - Kotlin
- [x] Codegen library - Scala
- [x] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin

If the change seems reasonable, I will make the gradle plugin and SBT changes

2023-03-18 01:39 UTC, kobylynskyi commented
Hey @velo 
Thanks for the contribution!
I like this feature.
Please address the comments I put in individual files. 
Also here are additional notes:
1 - Please fix the build, for some reason maven codegen fails with NPE: https://github.com/kobylynskyi/graphql-java-codegen/actions/runs/4445081094/jobs/7821033595?pr=1048
2 - If you can append a new record to the end of the configs description table in `codegen-options.md`.
3 - If you are familiar with Gradle/SBT plugins, please add support to those too.

Thank you!

2023-03-18 01:40 UTC, kobylynskyi requested changes

2023-03-18 01:40 UTC, kobylynskyi commented on src/main/java/com/kobylynskyi/graphql/codegen/generators/FreeMarkerTemplateFilesCreator.java
> +              template = FreeMarkerTemplatesRegistry.getCustomTemplates(mappingContext.getCustomTemplates().get(templateType));
1 - Don't make 2 map lookups (first `.containsKey()`, then `.get()`). Instead - do `.get()` and then check if the value is `null`.
2 - Use constant indentation of 4 spaces.

2023-03-18 01:40 UTC, kobylynskyi commented on src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
> +import java.util.EnumMap;
Unused import

2023-03-18 01:40 UTC, kobylynskyi commented on src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
> +      customTemplates.computeIfAbsent(from, k -> to);
Use 4 spaces indentation across all files

2023-03-18 01:40 UTC, kobylynskyi commented on src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenAnnotationsTest.java
> +    void generate_CustomTemplates_Type() throws Exception {
This test case is not related to annotations, so please move it to a separate test class `GraphQLCodegenCustomTemplatesTest`

2023-03-18 01:40 UTC, kobylynskyi commented on src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
> +     * Put custom template if absent.
```suggestion
     * Provide a path to a custom template for the specific FreeMarker template type (if absent).
```

2023-03-19 21:15 UTC, kobylynskyi submitted a review, later dismissed

2023-03-19 21:32 UTC, velo commented
Fixed scalafmt

2023-03-19 21:47 UTC, kobylynskyi approved these changes

2023-03-19 21:48 UTC, merged

2023-03-20 07:35 UTC, velo commented
Found a small buh on this, hope I can patch for the release