Adding Maven configuration setting to change the GraphQL grammar token limit
kobylynskyi/graphql-java-codegen pull request #1384
Opened 2023-11-08 13:39 UTC by yholkamp

---

### Description

Related to #1265: This PR adds a way to configure the maximum number of GraphQL grammar tokens the parser will process before throwing a 'denial of service' prevention warning. While Gradle users can easily override this, with Maven this does not appear to be feasible.

---

Changes were made to:
- [ ] Codegen library - Java
- [ ] Codegen library - Kotlin
- [ ] Codegen library - Scala
- [x] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin

2023-11-09 20:39 UTC, kobylynskyi commented
@yholkamp thanks for creating a PR. Can you please add the same option to Gradle and SBT plugins? Thank you!

2023-11-10 12:20 UTC, yholkamp commented
Apologies for the multiple pushes, the linter didn't quite agree with me.

@kobylynskyi thanks for your reply, after closer inspection of the GraphQL library, my initial approach seems to be too much of a shortcut. There are [4 distinct limits that can be configured on the parser](https://github.com/graphql-java/graphql-java/blob/86376aaee8fd507edd4e28e7a2a47b10b33b4e7a/src/main/java/graphql/parser/ParserOptions.java#L15-L53) and these require different values to be useful. The library imposes these to avoid scenarios where its used to process GraphQL queries on a server, which is very different from the purpose here. 

In order to make the plugin easy to use for the typical user, I've adjusted my changes to add a setting that skips this validation, while allowing it to be enabled when that's considered to be relevant. I'm hoping you'll agree with that approach.

2023-11-10 13:25 UTC, kobylynskyi requested changes
@yholkamp thanks for the changes! Agree with your approach to disable the validation completely as too many users of this plugin really want this feature to be disabled.

2023-11-10 13:25 UTC, kobylynskyi commented on plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
> +    private Boolean skipSchemaSizeLimit = true;
Please use `MappingConfigConstants.DEFAULT_` for the default value of this parameter (for consistency purposes).

2023-11-10 13:25 UTC, kobylynskyi commented on plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
> +    @Parameter(defaultValue = "true")
Please use `MappingConfigConstants.DEFAULT_` for the default value of this parameter (for consistency purposes).

2023-11-10 13:25 UTC, kobylynskyi commented on plugins/sbt/graphql-java-codegen-sbt-plugin/src/main/scala/io/github/dreamylost/graphql/codegen/GraphQLCodegenPlugin.scala
> +    skipSchemaSizeLimit            := true
Please use `MappingConfigConstants.DEFAULT_` for the default value of this parameter (for consistency purposes).

2023-11-10 13:25 UTC, kobylynskyi commented on plugins/sbt/graphql-java-codegen-sbt-plugin/src/main/scala/io/github/dreamylost/graphql/codegen/GraphQLCodegenPlugin.scala
> +            // .maxCharacters(Integer.MAX_VALUE)
Was this intentional?

2023-11-10 18:46 UTC, kobylynskyi approved these changes

2023-11-10 18:47 UTC, kobylynskyi commented
@yholkamp thanks for working on this! Will be included in 5.9.0 release

2023-11-10 18:47 UTC, merged