support generate normal public class for kotlin and scala.
kobylynskyi/graphql-java-codegen pull request #547
Opened 2021-02-19 05:49 UTC by jxnu-liguobin

https://github.com/kobylynskyi/graphql-java-codegen/issues/524.

Not support java 14 record.

2021-02-19 11:10 UTC, ntf commented
I quickly scan through the change set for Kotlin and notice that you also generate `equals` and `hashCode` which is great. 

LGTM for the kotlin change for #524

2021-02-20 02:21 UTC, kobylynskyi requested changes

2021-02-20 02:21 UTC, kobylynskyi commented on src/main/resources/templates/kotlin-lang/kotlinClassGraphqlType.ftl
> +<#if generateModelOpenClasses>
@jxnu-liguobin please merge nested if statement:
```ftl
<#if generateModelOpenClasses && equalsAndHashCode>
```

(relevant to all .ftl classes)

2021-02-20 02:28 UTC, kobylynskyi approved these changes
@jxnu-liguobin you are fast 🚀 
Merging it now.

2021-02-20 02:31 UTC, jxnu-liguobin commented
> @jxnu-liguobin you are fast 🚀
> Merging it now.

😸 We are in the daytime now.

2021-02-20 02:32 UTC, merged