Add ability to generate particular types as Java interfaces
kobylynskyi/graphql-java-codegen pull request #610
Opened 2021-03-24 17:24 UTC by donbeave

Implementation for this issue: https://github.com/kobylynskyi/graphql-java-codegen/issues/606

2021-03-24 18:13 UTC, donbeave commented
@kobylynskyi please check, only one task is failed is sonar task: https://github.com/kobylynskyi/graphql-java-codegen/runs/2186852139

But it looks like it's CI configuration issue, not something related to my changes in this PR.

2021-03-24 18:14 UTC, kobylynskyi commented
Yes, Sonar fails for all PRs from forked repos. 🥴

2021-03-25 00:32 UTC, kobylynskyi requested changes
@donbeave good job! Just one minor comment related to the codegen-options.md.
Once it is done - I am going to merge this to develop branch and release as part of 4.1.6.
Thanks again for the contribution! Much appreciate it.

2021-03-25 01:59 UTC, jxnu-liguobin commented on docs/codegen-options.md
> +| `typeInterfaces`                                      | Set(String)                                                           | Empty                                                  | Types that m
There may be ambiguity when use `@customInterface`, consider using `@asInterface` ?

2021-03-25 12:48 UTC, donbeave commented on docs/codegen-options.md
> +| `typeInterfaces`                                      | Set(String)                                                           | Empty                                                  | Types that m
@kobylynskyi correct, it's just a typo
@jxnu-liguobin thank you! nice catch!

2021-03-25 13:00 UTC, kobylynskyi approved these changes

2021-03-26 23:03 UTC, merged